FROM public.ecr.aws/s1x1t0a3/jvagent:latest

WORKDIR /var/task
COPY . /var/task/

RUN pip install --no-cache-dir jvdeploy
RUN pip install --no-cache-dir $(jvdeploy pip-get-packages --jvagent-path ./jvagent)

# {{ACTION_DEPENDENCIES}}
